const express = require("express");
const morgan = require("morgan");
const NodeCache = require("node-cache");

const app = express();

const PORT = 3007;

// ==========================================
// SERVER-SIDE CACHE
// ==========================================

const cache = new NodeCache({
    stdTTL: 60
});

// ==========================================
// MIDDLEWARE
// ==========================================

// Body parsing middleware
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Request logging middleware
app.use(morgan("dev"));

// ==========================================
// BACKGROUND TASK QUEUE
// ==========================================

const jobQueue = [];
let jobId = 1;
let processingJob = false;

// Add a background job
function addJob(type, data) {
    const job = {
        id: jobId++,
        type: type,
        data: data,
        status: "pending",
        createdAt: new Date().toISOString()
    };

    jobQueue.push(job);

    processJobs();

    return job;
}

// Process jobs one by one
async function processJobs() {
    if (processingJob) {
        return;
    }

    if (jobQueue.length === 0) {
        return;
    }

    processingJob = true;

    const job = jobQueue.shift();

    console.log(`Starting background job #${job.id}`);

    job.status = "processing";

    // Simulate background processing
    await new Promise((resolve) => {
        setTimeout(resolve, 3000);
    });

    job.status = "completed";
    job.completedAt = new Date().toISOString();

    console.log(`Background job #${job.id} completed`);

    processingJob = false;

    // Process next job
    processJobs();
}

// ==========================================
// HOME ROUTE
// ==========================================

app.get("/", (req, res) => {
    res.json({
        success: true,
        message: "Task 8 Advanced Server-Side Functionality is running!",
        features: [
            "Middleware",
            "Request Logging",
            "Background Task Queue",
            "Server-Side Caching"
        ]
    });
});

// ==========================================
// MIDDLEWARE TEST ROUTE
// ==========================================

app.post("/api/data", (req, res) => {
    console.log("Received request body:");

    console.log(req.body);

    res.json({
        success: true,
        message: "Request body processed successfully.",
        receivedData: req.body
    });
});

// ==========================================
// CREATE BACKGROUND JOB
// ==========================================

app.post("/api/jobs", (req, res) => {
    const { task } = req.body;

    if (!task) {
        return res.status(400).json({
            success: false,
            message: "Task is required."
        });
    }

    const job = addJob("background-task", {
        task: task
    });

    res.status(202).json({
        success: true,
        message: "Background job added successfully.",
        job: job
    });
});

// ==========================================
// VIEW JOB QUEUE
// ==========================================

app.get("/api/jobs", (req, res) => {
    res.json({
        success: true,
        queueLength: jobQueue.length,
        processingJob: processingJob,
        jobsWaiting: jobQueue
    });
});

// ==========================================
// CACHED DATA ROUTE
// ==========================================

app.get("/api/cached-data", (req, res) => {

    const cacheKey = "task8-data";

    // Check cache
    const cachedData = cache.get(cacheKey);

    if (cachedData) {

        console.log("Serving data from cache");

        return res.json({
            success: true,
            source: "cache",
            data: cachedData
        });
    }

    // Simulate expensive operation
    console.log("Generating new data...");

    const data = {
        message: "This data is generated by the server.",
        generatedAt: new Date().toISOString(),
        randomNumber: Math.floor(Math.random() * 100000)
    };

    // Store data in cache
    cache.set(cacheKey, data);

    res.json({
        success: true,
        source: "server",
        data: data
    });
});

// ==========================================
// CLEAR CACHE
// ==========================================

app.delete("/api/cache", (req, res) => {

    cache.flushAll();

    res.json({
        success: true,
        message: "Server-side cache cleared successfully."
    });
});

// ==========================================
// 404 ERROR HANDLER
// ==========================================

app.use((req, res) => {

    res.status(404).json({
        success: false,
        message: "Route not found."
    });
});

// ==========================================
// GLOBAL ERROR HANDLER
// ==========================================

app.use((err, req, res, next) => {

    console.error("Server error:", err);

    res.status(500).json({
        success: false,
        message: "Internal server error."
    });
});

// ==========================================
// START SERVER
// ==========================================

app.listen(PORT, () => {

    console.log("=================================");
    console.log("Task 8 - Advanced Server-Side Functionality");
    console.log("=================================");
    console.log(`Server running at http://localhost:${PORT}`);
    console.log("Middleware: Enabled");
    console.log("Request Logging: Enabled");
    console.log("Background Task Queue: Enabled");
    console.log("Server-Side Cache: Enabled");
    console.log("=================================");
});